package constants

object GameweekColumns {

  final var OPPONENT_TEAM = "opponentTeam"
  final var BONUS = "bonus"
  final var CLEAN_SHEETS = "cleanSheets"
  final var GOALS_CONCEDED = "goalsConceded"
  final var TOTAL_POINTS = "totalPoints"
  final var TEAM_A_SCORE = "teamAScore"
  final var INFLUENCE = "influence"
  final var SAVES = "saves"
  final var ASSISTS = "assists"
  final var TRANSFERS_IN = "transfersIn"
  final var CREATIVITY = "creativity"
  final var VALUE = "value"
  final var SELECTED = "selected"
  final var GOALS_SCORED = "goalsScored"
  final var MINUTES = "minutes"
  final var YELLOW_CARDS = "yellowCards"
  final var TEAM = "team"
  final var TRANSFERS_OUT = "transfersOut"
  final var ROUND = "round"
  final var POSITION = "position"
  final var THREAT = "threat"
  final var WEB_NAME = "webName"
  final var ICT_INDEX = "ictIndex"
  final var PENALTIES_SAVED = "penaltiesSaved"
  final var TEAM_H_SCORE = "teamHScore"
  final var HOME_FIXTURE = "homeFixture"
  final var MONTH = "month"
  final var YEAR = "year"

  // Dropped columns
  final var TRANSFERS_BALANCE = "transfersBalance"
  final var OWN_GOALS = "ownGoals"
  final var KICKOFF_TIME = "kickoffTime"
  final var RED_CARDS = "redCards"
  final var ELEMENT = "element"
  final var BPS = "bps"
  final var WAS_HOME = "wasHome"
  final var PENALTIES_MISSED = "penaltiesMissed"
  final var FIXTURE = "fixture"
}
