package constants

object GameweekColumns {

  final val OPPONENT_TEAM = "opponent_team"
  final val BONUS = "bonus"
  final val CLEAN_SHEETS = "clean_sheets"
  final val GOALS_CONCEDED = "goals_conceded"
  final val TOTAL_POINTS = "total_points"
  final val TEAM_A_SCORE = "team_a_score"
  final val INFLUENCE = "influence"
  final val SAVES = "saves"
  final val ASSISTS = "assists"
  final val TRANSFERS_IN = "transfers_in"
  final val CREATIVITY = "creativity"
  final val VALUE = "value"
  final val SELECTED = "selected"
  final val GOALS_SCORED = "goals_scored"
  final val MINUTES = "minutes"
  final val YELLOW_CARDS = "yellow_cards"
  final val TEAM = "team"
  final val TRANSFERS_OUT = "transfers_out"
  final val ROUND = "round"
  final val POSITION = "position"
  final val THREAT = "threat"
  final val ICT_INDEX = "ict_index"
  final val PENALTIES_SAVED = "penalties_saved"
  final val TEAM_H_SCORE = "team_h_score"
  final val HOME_FIXTURE = "home_fixture"
  final val MONTH = "month"
  final val YEAR = "year"

  // Dropped columns
  final val TRANSFERS_BALANCE = "transfers_balance"
  final val OWN_GOALS = "own_goals"
  final val KICKOFF_TIME = "kickoff_time"
  final val RED_CARDS = "red_cards"
  final val ELEMENT = "element"
  final val BPS = "bps"
  final val WAS_HOME = "was_home"
  final val PENALTIES_MISSED = "penalties_missed"
  final val FIXTURE = "fixture"
}
